language: php
sudo: required
dist: xenial
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3snapshot

addons:
  apt:
    packages:
      # required for php7.3snapshot
    - libzip4

before_script:
- rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
- composer install

script:
  - ./bin/phpunit --configuration tests/phpunit.xml.dist --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
